repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]
        types_or: [python, pyi]
  - repo: https://github.com/ambv/black
    rev: 24.3.0
    hooks:
      - id: black
      - id: black-jupyter
  # - repo: https://github.com/pycqa/flake8
  #   rev: "5.0.4" # pick a git hash / tag to point to
  #   hooks:
  #     - id: flake8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '\.xml$'
      - id: check-yaml
      - id: check-toml
      - id: check-json
      # - id: pretty-format-json
      - id: fix-encoding-pragma
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.9.0
  #   hooks:
  #     - id: mypy
  #       args: [--strict, --ignore-missing-imports]
