repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.282
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4" # pick a git hash / tag to point to
    hooks:
      - id: flake8
