name: EASIER build

on:
  push:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 0-6" # 3AM every day
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Create Virtual Environment and install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements/requirements.txt -c requirements/constraints.txt
        sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        pip install GDAL==3.2.3
        
    - name: Lint with flake8
      run: |
        source venv/bin/activate
        python3 -m flake8 code