name: EASIER build

on:
  push:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 0-6" # 3AM every day
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.14
      - name: Create Virtual Environment and install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements/requirements.txt -c requirements/constraints.txt
          sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update -y
          sudo apt-get install gdal-bin libgdal-dev -y
          pip install GDAL

      - name: Lint with flake8
        run: |
          source venv/bin/activate
          python3 -m flake8 code

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: "C04MMS895V5"
          # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
